### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by clifflo** [antkahn/flask-api-starter-kit#13]
Hi Ant how can we deal with CORS. I have a React application using Axios but when I do so there is a message saying that CORS is not allowed.

**Comment by clifflo** [comment]
Hi I just now figure out we will need to add flask-cors to the requirement.txt firstly and then run make server.install to update the dependencies and then add it to the server.py. If you don't mind will you add that to your current code?

**Comment by antkahn** [comment]
hi @clifflo !
I do not think flask-cors is required, since it won't be needed for every API this boilerplate is used for.
Your issue is a good documentation for addressing this problem though, thank you for it and for your response!
For those coming here with the same problem, you can find the documentation for flask-cors here: https://flask-cors.readthedocs.io/en/latest/

Closing this now
